import React,{useEffect,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import L from'leaflet';import'leaflet/dist/leaflet.css';import'./style.css';
const BASE=[{id:'luciane',label:'Luciane',address:'Rua Orlando Marcondes, Ponta Grossa - PR, Brasil',type:'start'},{id:'daniel',label:'Daniel',address:'Rua Tobias Moscoso, 38, Ponta Grossa - PR, Brasil',type:'stop'},{id:'evelyn',label:'Evelyn',address:'Rua Abatia, 140, Ponta Grossa - PR, Brasil',type:'stop'},{id:'empresa',label:'Odonto Excellence São Francisco',address:'Rua Eusébio de Queirós, 1120, Ponta Grossa - PR, Brasil',type:'end'}].map(x=>({...x,confirmed:true}));
const cleanVoice=t=>String(t||'').replace(/[\p{Extended_Pictographic}\uFE0F\u200D]/gu,'').replace(/\s{2,}/g,' ').trim();
const km=m=>m?`${(m/1000).toFixed(1)} km`:'—',mins=s=>s?`${Math.max(1,Math.round(s/60))} min`:'—';
function speak(t){if(!('speechSynthesis'in window))return;const text=cleanVoice(t);if(!text)return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='pt-BR';u.rate=.98;const vs=speechSynthesis.getVoices();u.voice=vs.find(v=>/google/i.test(v.name)&&/^pt/i.test(v.lang))||vs.find(v=>/pt-BR/i.test(v.lang))||null;speechSynthesis.speak(u)}
const reverse=a=>[...a].reverse().map((x,i,z)=>({...x,type:i===0?'start':i===z.length-1?'end':'stop'}));
function App(){const room=new URLSearchParams(location.search).get('sala')||'trabalho-daniel';const initial=()=>{try{const s=JSON.parse(localStorage.getItem('rota-fixed-v6'));if(s?.ida?.length)return s}catch{}return{ida:BASE,volta:reverse(BASE)}};const[trips,setTrips]=useState(initial),[dir,setDir]=useState('ida'),[route,setRoute]=useState(null),[routeStops,setRouteStops]=useState([]),[busy,setBusy]=useState(false),[status,setStatus]=useState('planejando'),[gps,setGps]=useState(null),[online,setOnline]=useState(1),[toast,setToast]=useState(''),[editing,setEditing]=useState(false);const map=useRef(),layer=useRef(),car=useRef(),ws=useRef(),watch=useRef(),auto=useRef(false);const stops=trips[dir];
const flash=t=>{setToast(t);setTimeout(()=>setToast(''),2600)};const save=t=>{setTrips(t);localStorage.setItem('rota-fixed-v6',JSON.stringify(t))};const send=x=>ws.current?.readyState===1&&ws.current.send(JSON.stringify(x));
useEffect(()=>{if(map.current)return;map.current=L.map('map',{zoomControl:false,preferCanvas:true}).setView([-25.095,-50.161],13);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map.current);L.control.zoom({position:'bottomright'}).addTo(map.current)},[]);
useEffect(()=>{let closed=false;const connect=()=>{const p=location.protocol==='https:'?'wss':'ws',s=new WebSocket(`${p}://${location.host}/ws?room=${encodeURIComponent(room)}&name=Rota`);ws.current=s;s.onmessage=e=>{try{const d=JSON.parse(e.data);if(d.type==='presence')setOnline(d.count||1);if(d.type==='gps')setGps(d.gps);if(d.type==='status')setStatus(d.status);if(d.type==='state'&&d.state?.trips){save(d.state.trips);setRoute(null);auto.current=false}}catch{}};s.onclose=()=>!closed&&setTimeout(connect,2500)};connect();return()=>{closed=true;speak('');ws.current?.close();if(watch.current)navigator.geolocation?.clearWatch(watch.current)}},[room]);
useEffect(()=>{if(!gps||!map.current)return;const ll=[gps.lat,gps.lon],ic=L.divIcon({className:'car',html:'▲',iconSize:[42,42],iconAnchor:[21,21]});if(car.current)car.current.setLatLng(ll);else car.current=L.marker(ll,{icon:ic,zIndexOffset:1000}).addTo(map.current);if(status==='em_rota')map.current.setView(ll,16,{animate:true})},[gps,status]);
const geocode=async s=>{if(Number.isFinite(s.lat)&&Number.isFinite(s.lon))return s;const r=await fetch(`/api/search?q=${encodeURIComponent(s.address)}`),j=await r.json();if(!j?.[0])throw Error(`Não localizei ${s.label}.`);return{...s,lat:+j[0].lat,lon:+j[0].lon,confirmed:true,display:s.address,approximate:!!j[0].approximate}};
const draw=(r,rs)=>{layer.current?.remove();const g=L.layerGroup().addTo(map.current);L.geoJSON(r.geometry,{style:{weight:7,opacity:.92,color:'#1769e0'}}).addTo(g);rs.forEach((s,i)=>L.marker([s.lat,s.lon],{icon:L.divIcon({className:'pin',html:`${i+1}`,iconSize:[34,34],iconAnchor:[17,17]})}).addTo(g).bindPopup(`<b>${s.label}</b><br>${s.address}`));layer.current=g;map.current.fitBounds(L.geoJSON(r.geometry).getBounds(),{padding:[45,45]})};
const calculate=async(silent=false)=>{if(busy)return;try{setBusy(true);let rs=[];for(const s of stops)rs.push(await geocode(s));const coords=rs.map(s=>`${s.lon},${s.lat}`).join(';'),u=`https://router.project-osrm.org/trip/v1/driving/${coords}?source=first&destination=last&roundtrip=false&overview=full&geometries=geojson&steps=true`,d=await(await fetch(u)).json();if(d.code!=='Ok')throw Error('Rota indisponível agora.');const r=d.trips[0];rs=d.waypoints.map((w,i)=>({i,o:w.waypoint_index})).sort((a,b)=>a.o-b.o).map(x=>rs[x.i]);draw(r,rs);setRoute(r);setRouteStops(rs);const t={...trips,[dir]:rs};save(t);send({type:'state',state:{trips:t,direction:dir}});if(!silent)flash('Rota pronta para iniciar')}catch(e){flash(e.message)}finally{setBusy(false)}};
useEffect(()=>{if(!map.current||auto.current||editing)return;auto.current=true;const id=setTimeout(()=>calculate(true),500);return()=>clearTimeout(id)},[dir,editing]);
const switchDir=d=>{setDir(d);setRoute(null);setRouteStops([]);auto.current=false;layer.current?.remove()};
const change=(id,v)=>{const t={...trips,[dir]:stops.map(s=>s.id===id?{...s,address:v,lat:null,lon:null,confirmed:false}:s)};save(t)};
const confirmGps=id=>navigator.geolocation?.getCurrentPosition(p=>{const patch={lat:p.coords.latitude,lon:p.coords.longitude,confirmed:true,display:'Local confirmado pelo GPS'};const t={...trips,[dir]:stops.map(s=>s.id===id?{...s,...patch}:s)};save(t);flash('Localização confirmada');auto.current=false},{enableHighAccuracy:true,timeout:12000});
const finishEdit=async()=>{setEditing(false);auto.current=false;setRoute(null);await calculate(true)};
const start=async()=>{if(!route)await calculate(true);if(!navigator.geolocation)return flash('GPS indisponível');if(!watch.current)watch.current=navigator.geolocation.watchPosition(p=>{const g={lat:p.coords.latitude,lon:p.coords.longitude,accuracy:p.coords.accuracy,speed:p.coords.speed,heading:p.coords.heading};setGps(g);send({type:'gps',...g})},()=>flash('Não foi possível acompanhar o GPS'),{enableHighAccuracy:true,maximumAge:1500,timeout:12000});setStatus('em_rota');send({type:'status',status:'em_rota'});speak('Viagem iniciada. Navegação ao vivo ativa.')};
const end=()=>{setStatus('concluida');send({type:'status',status:'concluida'});speak('Viagem concluída. Até a próxima.')};
return <div className={'app '+(status==='em_rota'?'driving':'')}>{toast&&<div className="toast">{toast}</div>}<header><div><b>Rota Daniel</b><small>{online} online • Ponta Grossa</small></div><button onClick={()=>setEditing(v=>!v)}>{editing?'Fechar':'Endereços'}</button></header><div className="tabs"><button className={dir==='ida'?'active':''} onClick={()=>switchDir('ida')}>IDA</button><button className={dir==='volta'?'active':''} onClick={()=>switchDir('volta')}>VOLTA</button></div><main><section className="mapWrap"><div id="map"/><div className="routeHud"><small>{status==='em_rota'?'EM VIAGEM':busy?'PREPARANDO ROTA':'ROTA PRONTA'}</small><strong>{status==='em_rota'?(routeStops[1]?.label?`Próxima: ${routeStops[1].label}`:'Navegação ativa'):(route?`${mins(route.duration)} • ${km(route.distance)}`:'Localizando endereços...')}</strong></div></section><aside>{editing?<div className="editor"><h2>Endereços fixos</h2><p>O check verde indica local confirmado. Ao alterar, a rota é reconstruída.</p>{stops.map((s,i)=><div className="address" key={s.id}><div className="addressTop"><b>{s.label}</b><span className={s.confirmed?'ok':'pending'}>{s.confirmed?'✓ Confirmado':'A confirmar'}</span></div><input value={s.address} onChange={e=>change(s.id,e.target.value)}/><button onClick={()=>confirmGps(s.id)}>Confirmar pelo GPS atual</button></div>)}<button className="primary" onClick={finishEdit}>Salvar e reconstruir rota</button></div>:<div className="summary"><div className="summaryHead"><div><small>{dir==='ida'?'IDA • CASA → EMPRESA':'VOLTA • EMPRESA → CASA'}</small><h1>{route?'Tudo pronto':'Preparando sua viagem'}</h1></div><span className="ready">{route?'✓':'…'}</span></div><div className="stops">{stops.map((s,i)=><div className="stop" key={s.id}><span>{i+1}</span><div><b>{s.label}</b><small>{s.address}</small></div><i>{s.confirmed?'✓':''}</i></div>)}</div>{route&&<div className="metrics"><div><b>{mins(route.duration)}</b><small>estimativa</small></div><div><b>{km(route.distance)}</b><small>distância</small></div></div>}{status==='em_rota'?<button className="danger" onClick={end}>Encerrar viagem</button>:<button className="start" disabled={busy} onClick={start}>{busy?'Preparando…':'Iniciar viagem'}</button>}<button className="secondary" onClick={()=>calculate(false)}>Recalcular melhor rota</button></div>}</aside></main></div>}
createRoot(document.getElementById('root')).render(<App/>);