import React,{useEffect,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import maplibregl from'maplibre-gl';
import'maplibre-gl/dist/maplibre-gl.css';
import'./style.css';

const FIXED=[
{id:'luciane',label:'Luciane',address:'Rua Orlando Marcondes, Colônia Dona Luíza, Ponta Grossa - PR, 84046-245, Brasil',lat:-25.14309,lon:-50.18036,type:'start',confirmed:true,fixed:true},
{id:'daniel',label:'Daniel',address:'Rua Tobias Moscoso, 38, Ronda, Ponta Grossa - PR, 84051-120, Brasil',lat:-25.1019501,lon:-50.1724167,type:'stop',confirmed:true,fixed:true},
{id:'evelyn',label:'Evelyn',address:'Rua Abatiá, 140, Nova Rússia, Ponta Grossa - PR, 84070-220, Brasil',lat:-25.0738906,lon:-50.1755799,type:'stop',confirmed:true,fixed:true},
{id:'empresa',label:'Odonto Excellence São Francisco',address:'Rua Antonil, 100, Uvaranas, Ponta Grossa - PR, 84032-190, Brasil',lat:-25.10550,lon:-50.09820,type:'end',confirmed:true,fixed:true}
];
const reverse=a=>[...a].reverse().map((x,i,z)=>({...x,type:i===0?'start':i===z.length-1?'end':'stop'}));
const defaults=()=>({ida:FIXED.map(x=>({...x})),volta:reverse(FIXED.map(x=>({...x})))});
const cleanVoice=t=>String(t||'').replace(/[\p{Extended_Pictographic}\uFE0F\u200D]/gu,'').replace(/\s{2,}/g,' ').trim();
const km=m=>Number.isFinite(m)?`${(m/1000).toFixed(1)} km`:'—';
const minText=s=>Number.isFinite(s)?`${Math.max(1,Math.round(s/60))} min`:'—';
const distText=m=>!Number.isFinite(m)?'—':m<1000?`${Math.max(10,Math.round(m/10)*10)} m`:`${(m/1000).toFixed(1)} km`;
const clock=ms=>new Intl.DateTimeFormat('pt-BR',{hour:'2-digit',minute:'2-digit'}).format(new Date(ms));
const weatherLabel=c=>c===0?'Céu limpo':c<=3?'Poucas nuvens':c===45||c===48?'Neblina':c>=51&&c<=67?'Chuva':c>=80&&c<=82?'Pancadas':c>=95?'Temporal':'Tempo variável';
function speak(t,interrupt=true){if(!('speechSynthesis'in window))return;const text=cleanVoice(t);if(!text)return;if(interrupt)speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='pt-BR';u.rate=.98;u.pitch=1;const vs=speechSynthesis.getVoices();u.voice=vs.find(v=>/google/i.test(v.name)&&/^pt/i.test(v.lang))||vs.find(v=>/pt-BR/i.test(v.lang))||vs.find(v=>/^pt/i.test(v.lang))||null;speechSynthesis.speak(u)}
const meters=(a,b)=>{if(!a||!b)return Infinity;const R=6371000,p1=a.lat*Math.PI/180,p2=b.lat*Math.PI/180,dp=(b.lat-a.lat)*Math.PI/180,dl=(b.lon-a.lon)*Math.PI/180,x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))};
const bearing=(a,b)=>{if(!a||!b)return null;const p1=a.lat*Math.PI/180,p2=b.lat*Math.PI/180,dl=(b.lon-a.lon)*Math.PI/180,y=Math.sin(dl)*Math.cos(p2),x=Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl);return(Math.atan2(y,x)*180/Math.PI+360)%360};
const gpsQuality=a=>!Number.isFinite(a)?{key:'off',label:'GPS aguardando'}:a<=8?{key:'excellent',label:'GPS excelente'}:a<=18?{key:'good',label:'GPS preciso'}:a<=35?{key:'fair',label:'GPS bom'}:{key:'weak',label:'GPS fraco'};
const blend=(prev,next,a)=>{if(!prev)return next;const k=a<=8?.96:a<=18?.88:a<=35?.72:.52;return{...next,lat:prev.lat+(next.lat-prev.lat)*k,lon:prev.lon+(next.lon-prev.lon)*k}};
const pointSegment=(p,a,b)=>{const lat0=p.lat*Math.PI/180,mLat=111320,mLon=111320*Math.cos(lat0),ax=(a.lon-p.lon)*mLon,ay=(a.lat-p.lat)*mLat,bx=(b.lon-p.lon)*mLon,by=(b.lat-p.lat)*mLat,dx=bx-ax,dy=by-ay,d2=dx*dx+dy*dy,t=d2?Math.max(0,Math.min(1,-(ax*dx+ay*dy)/d2)):0,x=ax+t*dx,y=ay+t*dy;return{distance:Math.hypot(x,y),t}};
const routeProgress=(point,geometry)=>{const cs=geometry?.coordinates;if(!point||!Array.isArray(cs)||cs.length<2)return{fraction:0,distance:Infinity,index:0};let total=0,cum=0,best=Infinity,bestCum=0,bestIndex=0;const segs=[];for(let i=1;i<cs.length;i++){const a={lat:cs[i-1][1],lon:cs[i-1][0]},b={lat:cs[i][1],lon:cs[i][0]},len=meters(a,b);segs.push({a,b,len,i});total+=len}for(const s of segs){const pr=pointSegment(point,s.a,s.b);if(pr.distance<best){best=pr.distance;bestCum=cum+s.len*pr.t;bestIndex=s.i}cum+=s.len}return{fraction:total?Math.max(0,Math.min(1,bestCum/total)):0,distance:best,index:bestIndex}};
const flattenSteps=r=>(r?.legs||[]).flatMap(l=>l.steps||[]).filter(s=>s?.maneuver?.location&&Array.isArray(s.geometry?.coordinates));
const stepNearest=(p,step)=>{const cs=step?.geometry?.coordinates||[];let best=Infinity;for(let i=1;i<cs.length;i++){best=Math.min(best,pointSegment(p,{lat:cs[i-1][1],lon:cs[i-1][0]},{lat:cs[i][1],lon:cs[i][0]}).distance)}return best};
const maneuverPoint=s=>s?.maneuver?.location?{lon:s.maneuver.location[0],lat:s.maneuver.location[1]}:null;
const maneuverText=s=>{if(!s)return'Continue pela rota';const m=s.maneuver||{},name=s.name?` na ${s.name}`:'',mod=m.modifier||'',type=m.type||'';if(type==='arrive')return'Você chegou ao destino';if(type==='roundabout'||type==='rotary')return`Entre na rotatória${name}`;if(type==='merge')return`Entre na via${name}`;if(type==='fork')return mod.includes('left')?`Mantenha-se à esquerda${name}`:`Mantenha-se à direita${name}`;if(type==='turn'||type==='end of road'||type==='new name'){if(mod.includes('left'))return`Vire à esquerda${name}`;if(mod.includes('right'))return`Vire à direita${name}`;if(mod.includes('uturn'))return'Faça o retorno quando for seguro';return`Siga em frente${name}`}if(type==='depart')return`Siga${name}`;return name?`Continue${name}`:'Continue em frente'};
const maneuverArrow=s=>{const m=s?.maneuver||{},mod=m.modifier||'',type=m.type||'';if(type==='roundabout'||type==='rotary')return'↻';if(type==='arrive')return'●';if(mod.includes('left'))return'↰';if(mod.includes('right'))return'↱';if(mod.includes('uturn'))return'↶';return'↑'};
const mapStyle={version:8,sources:{osm:{type:'raster',tiles:['https://a.tile.openstreetmap.org/{z}/{x}/{y}.png','https://b.tile.openstreetmap.org/{z}/{x}/{y}.png','https://c.tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'},satellite:{type:'raster',tiles:['https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'],tileSize:256,attribution:'Tiles © Esri'}},layers:[{id:'satellite',type:'raster',source:'satellite',layout:{visibility:'visible'}},{id:'osm',type:'raster',source:'osm',layout:{visibility:'none'}}]};

function App(){
 const room=new URLSearchParams(location.search).get('sala')||'trabalho-daniel';
 const initial=()=>{try{const v=JSON.parse(localStorage.getItem('rota-fixed-v9'));return v?.ida?.length?v:defaults()}catch{return defaults()}};
 const[trips,setTrips]=useState(initial),[dir,setDir]=useState('ida'),[route,setRoute]=useState(null),[routeStops,setRouteStops]=useState([]),[busy,setBusy]=useState(true),[status,setStatus]=useState('planejando'),[gps,setGps]=useState(null),[online,setOnline]=useState(1),[toast,setToast]=useState(''),[editing,setEditing]=useState(false),[menu,setMenu]=useState(false),[follow,setFollow]=useState(true),[nextIndex,setNextIndex]=useState(1),[weather,setWeather]=useState(null),[satellite,setSatellite]=useState(true),[tick,setTick]=useState(Date.now()),[routeFraction,setRouteFraction]=useState(0),[rerouting,setRerouting]=useState(false),[noticeOpen,setNoticeOpen]=useState(false),[noticeText,setNoticeText]=useState(''),[lastNotice,setLastNotice]=useState(null),[gpsState,setGpsState]=useState('starting'),[lastFixAt,setLastFixAt]=useState(0),[gpsError,setGpsError]=useState(''),[maneuver,setManeuver]=useState(null),[maneuverDistance,setManeuverDistance]=useState(null),[voiceOn,setVoiceOn]=useState(true),[offRouteMeters,setOffRouteMeters]=useState(0);
 const map=useRef(),routeMarkers=useRef([]),carMarker=useRef(),accuracyMarker=useRef(),ws=useRef(),watch=useRef(),lastAccepted=useRef(null),lastRaw=useRef(null),arrived=useRef(new Set()),cameraAt=useRef(0),offRouteCount=useRef(0),lastRerouteAt=useRef(0),gpsRestartAt=useRef(0),initialLocateDone=useRef(false),permissionState=useRef('prompt'),stepIndex=useRef(0),spoken=useRef(new Set()),lastHeading=useRef(null),wakeLock=useRef(null);
 const stops=trips[dir]||[],nextStop=routeStops[nextIndex]||routeStops.at(-1)||null,quality=gpsQuality(gps?.accuracy),speedKmh=Number.isFinite(gps?.speed)?Math.max(0,Math.round(gps.speed*3.6)):null,remaining=route?.duration?Math.max(0,route.duration*(status==='em_rota'?(1-routeFraction):1)):0,eta=route?clock(Date.now()+remaining*1000):'—',progress=route?Math.round((status==='em_rota'?routeFraction:0)*100):0,allFixed=stops.length>=2&&stops.every(s=>Number.isFinite(s.lat)&&Number.isFinite(s.lon)),gpsAge=lastFixAt?Math.max(0,Math.round((tick-lastFixAt)/1000)):null;
 const flash=t=>{setToast(t);setTimeout(()=>setToast(''),2800)},persist=t=>{setTrips(t);localStorage.setItem('rota-fixed-v9',JSON.stringify(t));return t},send=x=>ws.current?.readyState===1&&ws.current.send(JSON.stringify(x));
 const stopGps=()=>{if(watch.current!=null&&navigator.geolocation){navigator.geolocation.clearWatch(watch.current);watch.current=null}};
 const acceptGps=p=>{const raw={lat:p.coords.latitude,lon:p.coords.longitude,accuracy:p.coords.accuracy,speed:p.coords.speed,heading:p.coords.heading,at:Date.now()};if(!Number.isFinite(raw.lat)||!Number.isFinite(raw.lon))return;if(lastRaw.current){const dt=Math.max(.3,(raw.at-lastRaw.current.at)/1000),jump=meters(lastRaw.current,raw),derived=jump/dt;if(raw.accuracy>120&&lastRaw.current.accuracy<45)return;if(derived>75&&!Number.isFinite(raw.speed))return;if(!Number.isFinite(raw.heading)&&jump>3)raw.heading=bearing(lastRaw.current,raw)}if(Number.isFinite(raw.heading))lastHeading.current=raw.heading;else if(Number.isFinite(lastHeading.current))raw.heading=lastHeading.current;lastRaw.current=raw;const smooth=blend(lastAccepted.current,raw,raw.accuracy||99);lastAccepted.current=smooth;setGps(smooth);setLastFixAt(Date.now());setGpsState('live');setGpsError('');send({type:'gps',...smooth})};
 const gpsFail=e=>{const code=e?.code||0;if(code===1){permissionState.current='denied';setGpsState('denied');setGpsError('Localização bloqueada. Ative a permissão do navegador e atualize a página.');return}setGpsState('recovering');setGpsError(code===2?'Sinal de localização indisponível. Reconectando…':'GPS demorou a responder. Reconectando…')};
 const startGpsWatch=(force=false)=>{if(!navigator.geolocation){setGpsState('unsupported');setGpsError('Este navegador não oferece localização.');return false}if(watch.current!=null&&!force)return true;if(force)stopGps();setGpsState(s=>s==='denied'?'denied':'starting');watch.current=navigator.geolocation.watchPosition(acceptGps,gpsFail,{enableHighAccuracy:true,maximumAge:0,timeout:8000});gpsRestartAt.current=Date.now();return true};
 const requestInitialLocation=()=>{if(initialLocateDone.current||!navigator.geolocation)return;initialLocateDone.current=true;setGpsState('starting');navigator.geolocation.getCurrentPosition(p=>{acceptGps(p);startGpsWatch(false);map.current?.easeTo({center:[p.coords.longitude,p.coords.latitude],zoom:17,pitch:0,bearing:0,duration:350,essential:true})},gpsFail,{enableHighAccuracy:true,maximumAge:0,timeout:8000})};
 const recoverGps=()=>{if(permissionState.current==='denied'){location.reload();return}setGpsState('recovering');setGpsError('Reconectando GPS…');startGpsWatch(true);navigator.geolocation?.getCurrentPosition(p=>{acceptGps(p);setFollow(true);map.current?.easeTo({center:[p.coords.longitude,p.coords.latitude],zoom:17.6,pitch:status==='em_rota'?52:0,bearing:status==='em_rota'&&Number.isFinite(p.coords.heading)?p.coords.heading:0,duration:300,essential:true})},gpsFail,{enableHighAccuracy:true,maximumAge:0,timeout:8000})};

 useEffect(()=>{const id=setInterval(()=>setTick(Date.now()),1000);return()=>clearInterval(id)},[]);
 useEffect(()=>{if(!navigator.permissions?.query)return;let perm,cancelled=false;navigator.permissions.query({name:'geolocation'}).then(p=>{if(cancelled)return;perm=p;permissionState.current=p.state;p.onchange=()=>{permissionState.current=p.state;if(p.state==='granted'){initialLocateDone.current=false;requestInitialLocation()}if(p.state==='denied'){setGpsState('denied');setGpsError('Localização bloqueada. Ative a permissão e atualize a página.')}}}).catch(()=>{});return()=>{cancelled=true;if(perm)perm.onchange=null}},[]);
 useEffect(()=>{if(map.current)return;const m=new maplibregl.Map({container:'map',style:mapStyle,center:[-50.16,-25.095],zoom:13.2,pitch:0,bearing:0,dragRotate:true,touchZoomRotate:true,pitchWithRotate:true,touchPitch:true,bearingSnap:5,maxPitch:65,maxZoom:20.5,attributionControl:false,fadeDuration:80});m.addControl(new maplibregl.NavigationControl({showCompass:true,showZoom:true,visualizePitch:true}),'bottom-right');m.addControl(new maplibregl.AttributionControl({compact:true}),'bottom-left');m.on('dragstart',()=>setFollow(false));m.on('rotatestart',()=>setFollow(false));m.on('pitchstart',()=>setFollow(false));m.on('zoomstart',e=>{if(e.originalEvent)setFollow(false)});m.once('load',requestInitialLocation);map.current=m;return()=>{stopGps();m.remove();map.current=null}},[]);
 useEffect(()=>{const m=map.current;if(!m)return;const apply=()=>{if(!m.getLayer('satellite')||!m.getLayer('osm'))return;m.setLayoutProperty('satellite','visibility',satellite?'visible':'none');m.setLayoutProperty('osm','visibility',satellite?'none':'visible')};if(m.isStyleLoaded())apply();else m.once('load',apply)},[satellite]);
 useEffect(()=>{const onVisible=()=>{if(document.visibilityState==='visible'&&permissionState.current!=='denied'&&(!lastFixAt||Date.now()-lastFixAt>8000))recoverGps()};document.addEventListener('visibilitychange',onVisible);window.addEventListener('pageshow',onVisible);return()=>{document.removeEventListener('visibilitychange',onVisible);window.removeEventListener('pageshow',onVisible)}},[lastFixAt,status]);
 useEffect(()=>{if(permissionState.current!=='denied'&&gpsAge!=null&&gpsAge>8&&Date.now()-gpsRestartAt.current>7000){setGpsState('recovering');setGpsError('Sinal GPS perdido. Reconectando automaticamente…');startGpsWatch(true)}},[gpsAge]);
 useEffect(()=>{let stop=false;const load=async()=>{try{const r=await fetch('/api/weather');if(!r.ok)return;const j=await r.json();if(!stop)setWeather(j)}catch{}};load();const id=setInterval(load,10*60*1000);return()=>{stop=true;clearInterval(id)}},[]);
 useEffect(()=>{let closed=false;const connect=()=>{const p=location.protocol==='https:'?'wss':'ws',s=new WebSocket(`${p}://${location.host}/ws?room=${encodeURIComponent(room)}&name=Rotas%20Empresa`);ws.current=s;s.onmessage=e=>{try{const d=JSON.parse(e.data);if(d.type==='snapshot'){setOnline(d.count||1);if(d.status)setStatus(d.status)}if(d.type==='presence')setOnline(d.count||1);if(d.type==='status')setStatus(d.status);if(d.type==='state'&&d.state?.version==='5.2'&&d.state?.trips)persist(d.state.trips);if(d.type==='notification'&&d.notification?.text){setLastNotice(d.notification);flash(`Aviso: ${d.notification.text}`);if(d.notification.speak)speak(d.notification.text)}}catch{}};s.onclose=()=>!closed&&setTimeout(connect,1800)};connect();return()=>{closed=true;ws.current?.close()}},[room]);

 const clearRouteMarkers=()=>{routeMarkers.current.forEach(m=>m.remove());routeMarkers.current=[]};
 const draw=async(r,rs,fit=true)=>{const m=map.current;if(!m)return;if(!m.isStyleLoaded())await new Promise(resolve=>m.once('load',resolve));const data={type:'Feature',geometry:r.geometry,properties:{}};if(m.getSource('route'))m.getSource('route').setData(data);else{m.addSource('route',{type:'geojson',data});m.addLayer({id:'route-shadow',type:'line',source:'route',paint:{'line-color':'#03101b','line-width':14,'line-opacity':.5},layout:{'line-cap':'round','line-join':'round'}});m.addLayer({id:'route-line',type:'line',source:'route',paint:{'line-color':'#1689ff','line-width':7.5,'line-opacity':1},layout:{'line-cap':'round','line-join':'round'}})}clearRouteMarkers();rs.forEach((s,i)=>{const el=document.createElement('div');el.className='routePin';el.textContent=String(i+1);routeMarkers.current.push(new maplibregl.Marker({element:el,anchor:'center'}).setLngLat([s.lon,s.lat]).setPopup(new maplibregl.Popup({offset:22}).setHTML(`<b>${s.label}</b><br>${s.address}`)).addTo(m))});if(fit&&r.geometry?.coordinates?.length){const bounds=r.geometry.coordinates.reduce((b,c)=>b.extend(c),new maplibregl.LngLatBounds(r.geometry.coordinates[0],r.geometry.coordinates[0]));m.fitBounds(bounds,{padding:{top:120,bottom:115,left:55,right:55},maxZoom:15.8,duration:450})}};
 const buildLocalRoute=async list=>{const coords=list.map(s=>`${s.lon},${s.lat}`).join(';'),u=`https://router.project-osrm.org/route/v1/driving/${coords}?overview=full&geometries=geojson&steps=true&alternatives=false`,r=await fetch(u),j=await r.json();if(j.code!=='Ok'||!j.routes?.[0])throw Error('Rota temporariamente indisponível.');return j.routes[0]};
 const prepareGuidance=r=>{const steps=flattenSteps(r);stepIndex.current=0;spoken.current=new Set();const first=steps[1]||steps[0]||null;setManeuver(first);setManeuverDistance(first?meters(lastAccepted.current,maneuverPoint(first)):null)};
 const loadRoute=async(silent=false)=>{setBusy(true);try{let r,rs=stops;const unchanged=stops.every(s=>s.fixed!==false&&Number.isFinite(s.lat)&&Number.isFinite(s.lon));if(unchanged){const q=await fetch(`/api/route/${dir}`);if(q.ok){const j=await q.json();r=j.route;rs=j.stops}}if(!r&&allFixed)r=await buildLocalRoute(rs);if(!r)throw Error('A rota precisa de pontos válidos.');await draw(r,rs,true);setRoute(r);setRouteStops(rs);setNextIndex(1);setRouteFraction(0);setOffRouteMeters(0);arrived.current=new Set();prepareGuidance(r);if(!silent)flash('Rota carregada e pronta');return r}catch(e){flash(e.message||'Não foi possível carregar a rota.');return null}finally{setBusy(false)}};
 useEffect(()=>{setRoute(null);setRouteStops([]);setBusy(true);const id=setTimeout(()=>loadRoute(true),150);return()=>clearTimeout(id)},[dir]);
 const relocate=()=>{setFollow(true);if(gps){map.current?.easeTo({center:[gps.lon,gps.lat],zoom:17.8,pitch:status==='em_rota'?54:0,bearing:status==='em_rota'&&Number.isFinite(gps.heading)?gps.heading:map.current.getBearing(),offset:status==='em_rota'?[0,90]:[0,0],duration:280,essential:true});flash('Acompanhamento em tempo real ativado')}else recoverGps()};
 const rerouteFromGps=async current=>{if(rerouting||!current||Date.now()-lastRerouteAt.current<12000)return;const remainingStops=routeStops.slice(Math.min(nextIndex,routeStops.length-1));if(!remainingStops.length)return;try{setRerouting(true);lastRerouteAt.current=Date.now();if(voiceOn)speak('Recalculando a rota.');const origin={id:'gps',label:'Posição atual',lat:current.lat,lon:current.lon,address:'Posição atual'},r=await buildLocalRoute([origin,...remainingStops]);await draw(r,remainingStops,false);setRoute(r);setRouteStops(remainingStops);setNextIndex(0);setRouteFraction(0);setOffRouteMeters(0);offRouteCount.current=0;prepareGuidance(r);flash('Nova rota pronta');if(voiceOn)speak('Rota recalculada. Siga o novo caminho.')}catch{flash('Não foi possível recalcular agora. Vou tentar novamente.');lastRerouteAt.current=Date.now()-8000}finally{setRerouting(false)}};
 const updateGuidance=current=>{if(!route||status!=='em_rota')return;const steps=flattenSteps(route);if(steps.length<2)return;let idx=Math.min(stepIndex.current,steps.length-1),bestIdx=idx,best=Infinity;for(let i=Math.max(0,idx-1);i<Math.min(steps.length,idx+5);i++){const d=stepNearest(current,steps[i]);if(d<best){best=d;bestIdx=i}}if(bestIdx>idx)stepIndex.current=bestIdx;const next=steps[Math.min(stepIndex.current+1,steps.length-1)],mp=maneuverPoint(next),d=mp?meters(current,mp):null;setManeuver(next);setManeuverDistance(d);if(!voiceOn||!Number.isFinite(d))return;const keyBase=`${stepIndex.current}:${next?.maneuver?.type}:${next?.maneuver?.modifier||''}`;const phrase=maneuverText(next);for(const[tier,limit,prefix]of[['far',350,'Em 300 metros, '],['near',120,'Em 100 metros, '],['now',35,'Agora, ']]){const key=`${keyBase}:${tier}`;if(d<=limit&&!spoken.current.has(key)){spoken.current.add(key);speak(prefix+phrase);break}}};
 useEffect(()=>{const m=map.current;if(!gps||!m)return;const accuracy=Math.max(6,Math.min(80,gps.accuracy||30));if(!accuracyMarker.current){const halo=document.createElement('div');halo.className='gpsAccuracyHalo';accuracyMarker.current=new maplibregl.Marker({element:halo,anchor:'center'}).setLngLat([gps.lon,gps.lat]).addTo(m)}accuracyMarker.current.setLngLat([gps.lon,gps.lat]);accuracyMarker.current.getElement().style.setProperty('--gps-accuracy',`${Math.max(26,Math.min(96,accuracy*1.6))}px`);if(carMarker.current)carMarker.current.setLngLat([gps.lon,gps.lat]);else{const el=document.createElement('div');el.className='carMarker';el.innerHTML='<div class="carPulse"></div><div class="carArrow">▲</div><div class="liveDot"></div>';carMarker.current=new maplibregl.Marker({element:el,anchor:'center'}).setLngLat([gps.lon,gps.lat]).addTo(m)}const arrow=carMarker.current.getElement().querySelector('.carArrow');if(arrow&&Number.isFinite(gps.heading))arrow.style.transform=`rotate(${gps.heading}deg)`;if(route?.geometry){const rp=routeProgress(gps,route.geometry);setRouteFraction(rp.fraction);setOffRouteMeters(Math.round(rp.distance));if(status==='em_rota'){const reliable=(gps.accuracy||999)<=35;if(reliable&&rp.distance>55)offRouteCount.current+=1;else if(rp.distance<35)offRouteCount.current=0;if(offRouteCount.current>=2)rerouteFromGps(gps)}}if(status==='em_rota')updateGuidance(gps);if(status==='em_rota'&&follow&&Date.now()-cameraAt.current>240){cameraAt.current=Date.now();const moving=(speedKmh||0)>=3&&Number.isFinite(gps.heading);m.easeTo({center:[gps.lon,gps.lat],zoom:17.85,pitch:54,bearing:moving?gps.heading:m.getBearing(),offset:[0,95],duration:220,essential:true})}if(status==='em_rota'&&nextStop&&meters(gps,nextStop)<90&&!arrived.current.has(nextStop.id)){arrived.current.add(nextStop.id);if(voiceOn)speak(`Chegando em ${nextStop.label}.`);setNextIndex(i=>Math.min(i+1,Math.max(0,routeStops.length-1)))}},[gps,status,follow,nextStop,routeStops.length,route,rerouting,speedKmh,voiceOn]);
 useEffect(()=>{const manage=async()=>{if(status==='em_rota'&&'wakeLock'in navigator){try{wakeLock.current=await navigator.wakeLock.request('screen')}catch{}}else{try{await wakeLock.current?.release()}catch{}wakeLock.current=null}};manage();return()=>{try{wakeLock.current?.release()}catch{}}},[status]);
 const start=async()=>{let r=route;if(!r)r=await loadRoute(true);if(!r)return;if(!startGpsWatch(false))return;setStatus('em_rota');setFollow(true);setNextIndex(1);setRouteFraction(0);offRouteCount.current=0;prepareGuidance(r);send({type:'status',status:'em_rota'});if(voiceOn)speak('Viagem iniciada. Vou acompanhar sua posição e orientar o caminho.');setTimeout(relocate,120)};
 const end=()=>{setStatus('concluida');setFollow(false);send({type:'status',status:'concluida'});if(voiceOn)speak('Viagem concluída.')};
 const switchDir=d=>{if(d===dir)return;setDir(d);setStatus('planejando');setEditing(false);setMenu(false);setFollow(false)};
 const editAddress=(id,v)=>persist({...trips,[dir]:stops.map(s=>s.id===id?{...s,address:v,lat:null,lon:null,confirmed:false,fixed:false}:s)}),removeStop=id=>{const next=stops.filter(s=>s.id!==id);if(next.length<2)return flash('A rota precisa de origem e destino.');persist({...trips,[dir]:next});setRoute(null);flash('Parada removida')};
 const saveChanges=async()=>{setBusy(true);try{const resolved=[];for(const s of stops){if(Number.isFinite(s.lat)&&Number.isFinite(s.lon)){resolved.push({...s,confirmed:true});continue}const r=await fetch(`/api/search?q=${encodeURIComponent(s.address)}`),j=await r.json();if(!j?.[0])throw Error(`Não localizei ${s.label}. Verifique o endereço.`);resolved.push({...s,lat:+j[0].lat,lon:+j[0].lon,confirmed:true,fixed:false})}const t=persist({...trips,[dir]:resolved});send({type:'state',state:{version:'5.2',trips:t}});setEditing(false);const r=await buildLocalRoute(resolved);await draw(r,resolved,true);setRoute(r);setRouteStops(resolved);setNextIndex(1);setRouteFraction(0);prepareGuidance(r);flash('Rota atualizada e salva')}catch(e){flash(e.message||'Não foi possível salvar a alteração.')}finally{setBusy(false)}};
 const restoreFixed=()=>{const t=defaults();persist(t);setEditing(false);setRoute(null);setDir('ida');setTimeout(()=>loadRoute(false),120)},sendNotice=()=>{const text=cleanVoice(noticeText);if(!text)return flash('Digite a notificação.');const n={id:String(Date.now()),text,speak:true,at:Date.now(),from:'Central'};send({type:'notification',...n});setLastNotice(n);speak(text);flash('Notificação enviada e narrada');setNoticeText('');setNoticeOpen(false)},resetNorth=()=>{setFollow(false);map.current?.easeTo({bearing:0,pitch:0,duration:300,essential:true})};
 const routeStatus=rerouting?'Recalculando caminho':status==='em_rota'?'Navegação ao vivo':busy?'Carregando rota':'Rota pronta',routeHeadline=status==='em_rota'?(nextStop?`Próxima: ${nextStop.label}`:'Destino final'):(route?'Tudo pronto para sair':'Preparando viagem'),gpsLabel=gpsState==='denied'?'Localização bloqueada':gpsState==='recovering'?'Reconectando GPS':gpsState==='starting'?'Ativando GPS':quality.label;
 return <div className={'app '+(status==='em_rota'?'driving':'')}>
 {toast&&<div className="toast" role="status">{toast}</div>}
 {(gpsState==='denied'||(gpsState==='recovering'&&gpsAge>8))&&<div className={'gpsAlert '+(gpsState==='recovering'?'soft':'')}><div><b>{gpsState==='denied'?'Localização necessária':'Recuperando localização'}</b><small>{gpsError}</small></div><button onClick={gpsState==='denied'?()=>location.reload():recoverGps}>{gpsState==='denied'?'Atualizar site':'Tentar agora'}</button></div>}
 <header><div className="brand"><div className="brandMark">RE</div><div><b>Rotas Empresa</b><small>{online} online · {gpsState==='live'?'GPS ao vivo':'GPS preparando'}</small></div></div><button className="menuTrigger" aria-label="Abrir menu" onClick={()=>setMenu(true)}>☰</button></header>
 <div className="tabs"><button className={dir==='ida'?'active':''} onClick={()=>switchDir('ida')}>IDA <small>Casa → Empresa</small></button><button className={dir==='volta'?'active':''} onClick={()=>switchDir('volta')}>VOLTA <small>Empresa → Casa</small></button></div>
 <main><section className="mapWrap"><div id="map"/>
 <div className="routeHud"><div><small>{routeStatus.toUpperCase()}</small><strong>{routeHeadline}</strong><span>{route?`${minText(remaining)} · ${km(route.distance)} · chegada ${eta}`:'Usando rota interna salva'}</span></div><div className={'gpsPill '+quality.key}><b>{gpsLabel}</b><small>{Number.isFinite(gps?.accuracy)?`±${Math.round(gps.accuracy)} m · ${gpsAge??0}s`:'aguardando sinal'}</small></div></div>
 {status==='em_rota'&&maneuver&&<div className="maneuverCard"><div className="maneuverArrow">{maneuverArrow(maneuver)}</div><div><small>PRÓXIMA ORIENTAÇÃO</small><strong>{maneuverText(maneuver)}</strong><span>{distText(maneuverDistance)}</span></div></div>}
 <div className="gpsLivePanel"><span className={'gpsLiveLamp '+(gpsState==='live'?'on':'')}></span><div><b>{gpsState==='live'?'Localização ao vivo':'Localização em recuperação'}</b><small>{gpsState==='live'?`${Number.isFinite(gps?.accuracy)?`Precisão ±${Math.round(gps.accuracy)} m · `:''}${gpsAge===0?'agora':`há ${gpsAge??0}s`}`:gpsError||'Obtendo sinal GPS'}</small></div>{status==='em_rota'&&<i>{offRouteMeters<35?'Na rota':`${offRouteMeters} m da rota`}</i>}</div>
 <div className="mapTools"><button onClick={relocate}>◎ <span>Minha posição</span></button><button onClick={()=>setFollow(v=>!v)} className={follow?'active':''}>⌖ <span>{follow?'Seguindo':'Seguir'}</span></button><button onClick={()=>setVoiceOn(v=>!v)} className={voiceOn?'active':''}>◖ <span>{voiceOn?'Voz ligada':'Voz desligada'}</span></button><button onClick={resetNorth}>N <span>Norte</span></button><button onClick={()=>setSatellite(v=>!v)}>▦ <span>{satellite?'Satélite':'Mapa'}</span></button></div>
 {weather&&<div className="weatherMini"><small>AGORA</small><b>{Math.round(weather.temperature)}°</b><span>{weatherLabel(weather.code)}</span></div>}
 {status==='em_rota'&&<div className="driveHud"><div><small>CHEGADA</small><b>{eta}</b></div><div><small>FALTAM</small><b>{minText(remaining)}</b></div><div><small>VELOCIDADE</small><b>{speedKmh==null?'—':speedKmh}<span> km/h</span></b></div><div><small>PROGRESSO</small><b>{progress}%</b></div></div>}
 </section><aside>{editing?<div className="editor"><div className="sectionTitle"><div><small>CONFIGURAÇÃO</small><h2>Editar rota</h2></div><span className="statusOk">Salvo</span></div><p>A rota padrão já vem pronta. Altere somente quando precisar.</p>{stops.map((s,i)=><div className="address" key={s.id}><div className="addressTop"><b>{s.label}</b><span className="ok">✓ Salvo</span></div><input value={s.address} onChange={e=>editAddress(s.id,e.target.value)}/>{i>0&&i<stops.length-1&&<button className="remove" onClick={()=>removeStop(s.id)}>Remover desta viagem</button>}</div>)}<button className="primary" disabled={busy} onClick={saveChanges}>Salvar e atualizar rota</button><button className="secondary" onClick={restoreFixed}>Restaurar rota padrão</button></div>:<div className="summary"><div className="summaryHead"><div><small>{dir==='ida'?'IDA · ROTA PADRÃO':'VOLTA · ROTA PADRÃO'}</small><h1>{route?'Pronto para iniciar':'Preparando rota'}</h1><p>{route?'Endereços fixos reconhecidos e caminho carregado.':'Carregando a rota interna.'}</p></div><span className={'ready '+(route?'done':'')}>{route?'✓':'…'}</span></div><div className="stops">{stops.map((s,i)=><div className="stop" key={s.id}><span>{i+1}</span><div><b>{s.label}</b><small>{s.address}</small></div><i className="confirmed">✓</i></div>)}</div>{route&&<div className="metrics"><div><small>Chegada estimada</small><b>{eta}</b></div><div><small>Duração</small><b>{minText(remaining)}</b></div><div><small>Distância</small><b>{km(route.distance)}</b></div></div>}{lastNotice&&<div className="lastNotice"><small>ÚLTIMO AVISO</small><b>{lastNotice.text}</b></div>}{status==='em_rota'?<><div className="navStatus"><span className={'signal '+quality.key}></span><div><b>{rerouting?'Recalculando automaticamente':gpsLabel}</b><small>{Number.isFinite(gps?.accuracy)?`Precisão ±${Math.round(gps.accuracy)} m · atualização ${gpsAge===0?'agora':`há ${gpsAge}s`}`:'Obtendo localização'}</small></div></div><button className="danger" onClick={end}>Encerrar viagem</button></>:<button className="start" disabled={busy||!route} onClick={start}>{busy?'Preparando…':'Iniciar viagem'}</button>}<button className="secondary" disabled={busy} onClick={()=>loadRoute(false)}>Atualizar rota</button></div>}</aside></main>
 {menu&&<div className="drawerBackdrop" onClick={()=>setMenu(false)}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawerHead"><div><b>Rotas Empresa</b><small>Central da viagem</small></div><button onClick={()=>setMenu(false)}>×</button></div><nav><button onClick={()=>{setEditing(false);setMenu(false)}}><span className="navIcon">⌖</span><span>Rota<small>Mapa e viagem pronta</small></span></button><button onClick={()=>{setEditing(true);setMenu(false)}}><span className="navIcon">✎</span><span>Editar rota<small>Alterar ou remover paradas</small></span></button><button onClick={()=>{setMenu(false);relocate()}}><span className="navIcon">◎</span><span>Minha posição<small>Retomar acompanhamento ao vivo</small></span></button><button onClick={()=>{setMenu(false);setNoticeOpen(true)}}><span className="navIcon">◖</span><span>Enviar notificação<small>Mensagem narrada para os conectados</small></span></button><button onClick={()=>setVoiceOn(v=>!v)}><span className="navIcon">◖</span><span>Orientação por voz<small>{voiceOn?'Ativada':'Desativada'}</small></span></button><button onClick={()=>{setMenu(false);setSatellite(v=>!v)}}><span className="navIcon">▦</span><span>Alternar mapa<small>Mapa ou satélite</small></span></button><button onClick={()=>{setMenu(false);loadRoute(false)}}><span className="navIcon">↻</span><span>Atualizar rota<small>Recarregar caminho</small></span></button></nav><div className="drawerTrips"><b>VIAGEM</b><button className={dir==='ida'?'active':''} onClick={()=>switchDir('ida')}>Ida · Casa → Empresa</button><button className={dir==='volta'?'active':''} onClick={()=>switchDir('volta')}>Volta · Empresa → Casa</button></div><div className="devCredit">Em desenvolvimento por Daniel</div></aside></div>}
 {noticeOpen&&<div className="modalBackdrop" onClick={()=>setNoticeOpen(false)}><div className="noticeModal" onClick={e=>e.stopPropagation()}><div className="modalHead"><div><small>COMUNICAÇÃO</small><h2>Notificação narrada</h2></div><button onClick={()=>setNoticeOpen(false)}>×</button></div><p>A mensagem será exibida e narrada nos dispositivos conectados com o site ativo.</p><textarea value={noticeText} onChange={e=>setNoticeText(e.target.value)} maxLength={240} placeholder="Ex.: Aguarde na entrada, estou chegando."/><div className="charCount">{noticeText.length}/240</div><button className="primary" onClick={sendNotice}>Enviar e narrar</button></div></div>}
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
