import express from'express';
import{createServer}from'http';
import{WebSocketServer,WebSocket}from'ws';
import{Pool}from'pg';
import path from'path';
import{fileURLToPath}from'url';
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const app=express();app.disable('x-powered-by');app.use(express.json({limit:'64kb'}));
app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Permissions-Policy','geolocation=(self), microphone=(), camera=()');if(req.path.startsWith('/api/'))res.setHeader('Cache-Control','no-store');next()});

const FIXED=[
{id:'luciane',label:'Luciane',address:'Rua Orlando Marcondes, Colônia Dona Luíza, Ponta Grossa - PR, 84046-245, Brasil',lat:-25.14309,lon:-50.18036,type:'start',confirmed:true,fixed:true},
{id:'daniel',label:'Daniel',address:'Rua Tobias Moscoso, 38, Ronda, Ponta Grossa - PR, 84051-120, Brasil',lat:-25.1019501,lon:-50.1724167,type:'stop',confirmed:true,fixed:true},
{id:'evelyn',label:'Evelyn',address:'Rua Abatiá, 140, Nova Rússia, Ponta Grossa - PR, 84070-220, Brasil',lat:-25.0738906,lon:-50.1755799,type:'stop',confirmed:true,fixed:true},
{id:'empresa',label:'Odonto Excellence São Francisco',address:'Rua Antonil, 100, Uvaranas, Ponta Grossa - PR, 84032-190, Brasil',lat:-25.10550,lon:-50.09820,type:'end',confirmed:true,fixed:true}
];
const reverseStops=a=>[...a].reverse().map((x,i,z)=>({...x,type:i===0?'start':i===z.length-1?'end':'stop'}));
const ROUTES={ida:FIXED,volta:reverseStops(FIXED)};
const cache=new Map(),routeCache=new Map();let weatherCache=null;
const historyMemory=[];
let db=null,dbReady=false;
if(process.env.DATABASE_URL){
 db=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL.includes('localhost')?false:{rejectUnauthorized:false}});
 db.query(`CREATE TABLE IF NOT EXISTS trip_history(
   id text PRIMARY KEY,
   direction text NOT NULL,
   status text NOT NULL,
   started_at timestamptz NOT NULL,
   ended_at timestamptz,
   stops jsonb NOT NULL DEFAULT '[]'::jsonb,
   passengers jsonb NOT NULL DEFAULT '{}'::jsonb,
   distance_m double precision,
   duration_s double precision,
   created_at timestamptz NOT NULL DEFAULT now(),
   updated_at timestamptz NOT NULL DEFAULT now()
 )`).then(()=>{dbReady=true;console.log('Trip history: PostgreSQL ready')}).catch(e=>console.error('Trip history DB unavailable:',e.message));
}else console.log('Trip history: DATABASE_URL not configured, using runtime memory + browser backup');

const safeDirection=v=>v==='volta'?'volta':'ida';
const safeStops=v=>Array.isArray(v)?v.slice(0,12).map(s=>({id:String(s?.id||'').slice(0,40),label:String(s?.label||'').slice(0,80),address:String(s?.address||'').slice(0,220),lat:Number.isFinite(+s?.lat)?+s.lat:null,lon:Number.isFinite(+s?.lon)?+s.lon:null})):[];
const safePassengers=v=>{const out={};if(v&&typeof v==='object')for(const[k,val]of Object.entries(v).slice(0,20))out[String(k).slice(0,50)]=Boolean(val);return out};
const cleanResult=(lat,lon,display,title,subtitle,approximate=false)=>({lat:+lat,lon:+lon,display:String(display||'').replace(/,\s*,/g,',').trim(),title:String(title||display||'Local'),subtitle:String(subtitle||'Ponta Grossa • Paraná'),approximate});
async function photon(q){const query=/ponta grossa/i.test(q)?q:`${q}, Ponta Grossa, Paraná, Brasil`;const r=await fetch(`https://photon.komoot.io/api/?limit=8&lang=pt&q=${encodeURIComponent(query)}`,{headers:{'User-Agent':'RotasEmpresa/5.3'}});if(!r.ok)return[];const j=await r.json();return(j.features||[]).map(f=>{const p=f.properties||{},c=f.geometry?.coordinates||[];const title=[p.name||p.street,p.housenumber].filter(Boolean).join(', ');const display=[p.name,p.street,p.housenumber,p.district,p.city,p.state].filter(Boolean).join(', ');return cleanResult(c[1],c[0],display,title,[p.district,p.city,p.state].filter(Boolean).join(' • '),!p.housenumber)}).filter(x=>Number.isFinite(x.lat)&&Number.isFinite(x.lon)&&(/Ponta Grossa/i.test(x.display)||/Ponta Grossa/i.test(x.subtitle)))}
async function nominatim(q){const query=/ponta grossa/i.test(q)?q:`${q}, Ponta Grossa, PR, Brasil`;const r=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=6&countrycodes=br&addressdetails=1&q=${encodeURIComponent(query)}`,{headers:{'User-Agent':'RotasEmpresa/5.3','Accept-Language':'pt-BR'}});if(!r.ok)return[];const j=await r.json();return(j||[]).filter(x=>/Ponta Grossa/i.test(x.display_name||'')).map(x=>{const a=x.address||{},title=[a.road||a.pedestrian||a.neighbourhood||x.name,a.house_number].filter(Boolean).join(', ');return cleanResult(x.lat,x.lon,x.display_name,title,[a.suburb||a.neighbourhood,a.city||a.town||'Ponta Grossa',a.state].filter(Boolean).join(' • '),!a.house_number)})}
app.get('/api/search',async(req,res)=>{const q=String(req.query.q||'').trim().slice(0,180);if(q.length<3)return res.json([]);const fixed=FIXED.filter(x=>x.address.toLowerCase().includes(q.toLowerCase())||x.label.toLowerCase().includes(q.toLowerCase()));if(fixed.length)return res.json(fixed.map(x=>cleanResult(x.lat,x.lon,x.address,x.label,'Ponta Grossa • Paraná',false)));const key=q.toLowerCase();if(cache.has(key)&&Date.now()-cache.get(key).at<10*60*1000)return res.json(cache.get(key).data);try{let data=await photon(q);if(data.length<3)data=[...data,...await nominatim(q)];const seen=new Set();data=data.filter(x=>{const k=`${x.lat.toFixed(5)}:${x.lon.toFixed(5)}`;if(seen.has(k))return false;seen.add(k);return true}).slice(0,8);cache.set(key,{at:Date.now(),data});res.json(data)}catch{res.status(502).json([])}});
async function buildRoute(dir){const key=safeDirection(dir),cached=routeCache.get(key);if(cached&&Date.now()-cached.at<30*60*1000)return cached.data;const stops=ROUTES[key],coords=stops.map(s=>`${s.lon},${s.lat}`).join(';'),url=`https://router.project-osrm.org/route/v1/driving/${coords}?overview=full&geometries=geojson&steps=true&alternatives=false`,r=await fetch(url,{headers:{'User-Agent':'RotasEmpresa/5.3'}});if(!r.ok)throw Error('router unavailable');const j=await r.json();if(j.code!=='Ok'||!j.routes?.[0])throw Error('route unavailable');const data={direction:key,stops,route:j.routes[0],generatedAt:Date.now()};routeCache.set(key,{at:Date.now(),data});return data}
app.get('/api/route/:dir',async(req,res)=>{try{res.json(await buildRoute(req.params.dir))}catch{const key=safeDirection(req.params.dir),stale=routeCache.get(key);if(stale)return res.json({...stale.data,stale:true});res.status(503).json({error:'route_unavailable',stops:ROUTES[key]})}});
app.get('/api/bootstrap',(req,res)=>res.json({stops:{ida:ROUTES.ida,volta:ROUTES.volta},ready:true,version:'5.3.0'}));
app.get('/api/weather',async(req,res)=>{try{if(weatherCache&&Date.now()-weatherCache.at<10*60*1000)return res.json(weatherCache.data);const r=await fetch('https://api.open-meteo.com/v1/forecast?latitude=-25.095&longitude=-50.161&current=temperature_2m,weather_code,precipitation,wind_speed_10m&timezone=America%2FSao_Paulo',{headers:{'User-Agent':'RotasEmpresa/5.3'}});if(!r.ok)throw Error();const j=await r.json();const data={temperature:j.current?.temperature_2m??null,code:j.current?.weather_code??null,precipitation:j.current?.precipitation??null,wind:j.current?.wind_speed_10m??null,at:Date.now()};weatherCache={at:Date.now(),data};res.json(data)}catch{if(weatherCache)return res.json({...weatherCache.data,stale:true});res.status(503).json({error:'weather_unavailable'})}});

app.get('/api/history',async(req,res)=>{try{if(dbReady){const q=await db.query('SELECT id,direction,status,started_at AS "startedAt",ended_at AS "endedAt",stops,passengers,distance_m AS "distance",duration_s AS "duration" FROM trip_history ORDER BY started_at DESC LIMIT 200');return res.json({storage:'postgres',items:q.rows})}return res.json({storage:'memory',items:[...historyMemory].reverse().slice(0,200)})}catch{res.status(500).json({error:'history_read_failed'})}});
app.post('/api/history/start',async(req,res)=>{try{const body=req.body||{},id=String(body.id||`trip-${Date.now()}`).slice(0,80),record={id,direction:safeDirection(body.direction),status:'started',startedAt:new Date(body.startedAt||Date.now()).toISOString(),endedAt:null,stops:safeStops(body.stops),passengers:safePassengers(body.passengers),distance:Number.isFinite(+body.distance)?+body.distance:null,duration:Number.isFinite(+body.duration)?+body.duration:null};if(dbReady)await db.query('INSERT INTO trip_history(id,direction,status,started_at,stops,passengers,distance_m,duration_s) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(id) DO UPDATE SET direction=EXCLUDED.direction,status=EXCLUDED.status,started_at=EXCLUDED.started_at,stops=EXCLUDED.stops,passengers=EXCLUDED.passengers,distance_m=EXCLUDED.distance_m,duration_s=EXCLUDED.duration_s,updated_at=now()',[record.id,record.direction,record.status,record.startedAt,JSON.stringify(record.stops),JSON.stringify(record.passengers),record.distance,record.duration]);else{const i=historyMemory.findIndex(x=>x.id===id);if(i>=0)historyMemory[i]=record;else historyMemory.push(record)}res.json({ok:true,storage:dbReady?'postgres':'memory',record})}catch(e){res.status(500).json({error:'history_start_failed'})}});
app.patch('/api/history/:id/complete',async(req,res)=>{try{const id=String(req.params.id).slice(0,80),body=req.body||{},endedAt=new Date(body.endedAt||Date.now()).toISOString(),passengers=safePassengers(body.passengers),distance=Number.isFinite(+body.distance)?+body.distance:null,duration=Number.isFinite(+body.duration)?+body.duration:null;if(dbReady){const q=await db.query('UPDATE trip_history SET status=$2,ended_at=$3,passengers=$4,distance_m=COALESCE($5,distance_m),duration_s=COALESCE($6,duration_s),updated_at=now() WHERE id=$1 RETURNING id,direction,status,started_at AS "startedAt",ended_at AS "endedAt",stops,passengers,distance_m AS "distance",duration_s AS "duration"',[id,'completed',endedAt,JSON.stringify(passengers),distance,duration]);return res.json({ok:true,storage:'postgres',record:q.rows[0]||null})}const i=historyMemory.findIndex(x=>x.id===id);if(i>=0)historyMemory[i]={...historyMemory[i],status:'completed',endedAt,passengers,distance:distance??historyMemory[i].distance,duration:duration??historyMemory[i].duration};res.json({ok:true,storage:'memory',record:i>=0?historyMemory[i]:null})}catch{res.status(500).json({error:'history_complete_failed'})}});

app.use(express.static(path.join(__dirname,'dist'),{maxAge:'1h'}));
app.get('/health',(req,res)=>res.json({ok:true,service:'Rotas Empresa',version:'5.3.0',historyStorage:dbReady?'postgres':'memory',time:new Date().toISOString()}));
app.use((req,res)=>res.sendFile(path.join(__dirname,'dist','index.html')));
const server=createServer(app),wss=new WebSocketServer({server,path:'/ws'}),rooms=new Map();
const getRoom=id=>{if(!rooms.has(id))rooms.set(id,{clients:new Set(),state:null,messages:[],gps:null,status:'planejando',notifications:[]});return rooms.get(id)};
const broadcast=(room,payload,except=null)=>{const data=JSON.stringify(payload);for(const c of room.clients)if(c!==except&&c.readyState===WebSocket.OPEN)c.send(data)};
const presence=room=>broadcast(room,{type:'presence',count:room.clients.size});
wss.on('connection',(ws,req)=>{const u=new URL(req.url,'http://localhost'),roomId=(u.searchParams.get('room')||'geral').slice(0,80),name=(u.searchParams.get('name')||'Passageiro').slice(0,40),room=getRoom(roomId);room.clients.add(ws);ws.send(JSON.stringify({type:'snapshot',state:room.state,messages:room.messages.slice(-100),gps:room.gps,status:room.status,count:room.clients.size,notifications:room.notifications.slice(-20)}));presence(room);ws.on('message',raw=>{try{const m=JSON.parse(raw.toString());if(m.type==='message'){const msg={id:String(m.id||Date.now()),name:String(m.name||name).slice(0,40),text:String(m.text||'').slice(0,1000),at:Date.now()};if(msg.text){room.messages.push(msg);room.messages=room.messages.slice(-100);broadcast(room,{type:'message',message:msg})}}if(m.type==='notification'){const n={id:String(m.id||Date.now()),text:String(m.text||'').slice(0,240),speak:m.speak!==false,from:String(m.from||name).slice(0,40),at:Date.now()};if(n.text){room.notifications.push(n);room.notifications=room.notifications.slice(-20);broadcast(room,{type:'notification',notification:n},ws)}}if(m.type==='gps'&&Number.isFinite(m.lat)&&Number.isFinite(m.lon)){room.gps={lat:m.lat,lon:m.lon,accuracy:m.accuracy||null,speed:m.speed||null,heading:m.heading||null,at:Date.now(),name};broadcast(room,{type:'gps',gps:room.gps})}if(m.type==='state'&&m.state){room.state=m.state;broadcast(room,{type:'state',state:room.state},ws)}if(m.type==='status'){room.status=String(m.status||'planejando').slice(0,40);broadcast(room,{type:'status',status:room.status})}}catch{}});ws.on('close',()=>{room.clients.delete(ws);presence(room);if(room.clients.size===0)setTimeout(()=>{if(room.clients.size===0)rooms.delete(roomId)},1000*60*60*3)})});
const port=process.env.PORT||3000;
server.listen(port,'0.0.0.0',()=>console.log(`Rotas Empresa v5.3 online na porta ${port}`));