import express from'express';import{createServer}from'http';import{WebSocketServer,WebSocket}from'ws';import path from'path';import{fileURLToPath}from'url';
const __dirname=path.dirname(fileURLToPath(import.meta.url));const app=express();app.disable('x-powered-by');app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Permissions-Policy','geolocation=(self), microphone=(), camera=()');next()});
const cache=new Map();
const cleanResult=(lat,lon,display,title,subtitle,approximate=false)=>({lat:+lat,lon:+lon,display:String(display||'').replace(/,\s*,/g,',').trim(),title:String(title||display||'Local'),subtitle:String(subtitle||'Ponta Grossa • Paraná'),approximate});
async function photon(q){const query=/ponta grossa/i.test(q)?q:`${q}, Ponta Grossa, Paraná, Brasil`;const r=await fetch(`https://photon.komoot.io/api/?limit=8&lang=pt&q=${encodeURIComponent(query)}`,{headers:{'User-Agent':'RotaDaniel/4.0'}});if(!r.ok)return[];const j=await r.json();return(j.features||[]).map(f=>{const p=f.properties||{},c=f.geometry?.coordinates||[];const title=[p.name||p.street,p.housenumber].filter(Boolean).join(', ');const display=[p.name,p.street,p.housenumber,p.district,p.city,p.state].filter(Boolean).join(', ');return cleanResult(c[1],c[0],display,title,[p.district,p.city,p.state].filter(Boolean).join(' • '),!p.housenumber)}).filter(x=>Number.isFinite(x.lat)&&Number.isFinite(x.lon)&&(/Ponta Grossa/i.test(x.display)||/Ponta Grossa/i.test(x.subtitle)))}
async function nominatim(q){const query=/ponta grossa/i.test(q)?q:`${q}, Ponta Grossa, PR, Brasil`;const r=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=6&countrycodes=br&addressdetails=1&q=${encodeURIComponent(query)}`,{headers:{'User-Agent':'RotaDaniel/4.0','Accept-Language':'pt-BR'}});if(!r.ok)return[];const j=await r.json();return(j||[]).filter(x=>/Ponta Grossa/i.test(x.display_name||'')).map(x=>{const a=x.address||{},title=[a.road||a.pedestrian||a.neighbourhood||x.name,a.house_number].filter(Boolean).join(', ');return cleanResult(x.lat,x.lon,x.display_name,title,[a.suburb||a.neighbourhood,a.city||a.town||'Ponta Grossa',a.state].filter(Boolean).join(' • '),!a.house_number)})}
app.get('/api/search',async(req,res)=>{const q=String(req.query.q||'').trim().slice(0,180);if(q.length<3)return res.json([]);const key=q.toLowerCase();if(cache.has(key)&&Date.now()-cache.get(key).at<10*60*1000)return res.json(cache.get(key).data);try{let data=await photon(q);if(data.length<3)data=[...data,...await nominatim(q)];const seen=new Set();data=data.filter(x=>{const k=`${x.lat.toFixed(5)}:${x.lon.toFixed(5)}`;if(seen.has(k))return false;seen.add(k);return true}).slice(0,8);cache.set(key,{at:Date.now(),data});res.json(data)}catch{res.status(502).json([])}});
app.use(express.static(path.join(__dirname,'dist'),{maxAge:'1h'}));app.get('/health',(req,res)=>res.json({ok:true,service:'Rota Daniel',version:'4.0.0',time:new Date().toISOString()}));app.use((req,res)=>res.sendFile(path.join(__dirname,'dist','index.html')));
const server=createServer(app),wss=new WebSocketServer({server,path:'/ws'}),rooms=new Map();const getRoom=id=>{if(!rooms.has(id))rooms.set(id,{clients:new Set(),state:null,messages:[],gps:null,status:'planejando',notifications:[]});return rooms.get(id)};const broadcast=(room,payload,except=null)=>{const data=JSON.stringify(payload);for(const c of room.clients)if(c!==except&&c.readyState===WebSocket.OPEN)c.send(data)};const presence=room=>broadcast(room,{type:'presence',count:room.clients.size});
wss.on('connection',(ws,req)=>{const u=new URL(req.url,'http://localhost'),roomId=(u.searchParams.get('room')||'geral').slice(0,80),name=(u.searchParams.get('name')||'Passageiro').slice(0,40),room=getRoom(roomId);room.clients.add(ws);ws.send(JSON.stringify({type:'snapshot',state:room.state,messages:room.messages.slice(-100),gps:room.gps,status:room.status,count:room.clients.size,notifications:room.notifications.slice(-20)}));presence(room);ws.on('message',raw=>{try{const m=JSON.parse(raw.toString());if(m.type==='message'){const msg={id:String(m.id||Date.now()),name:String(m.name||name).slice(0,40),text:String(m.text||'').slice(0,1000),at:Date.now()};if(msg.text){room.messages.push(msg);room.messages=room.messages.slice(-100);broadcast(room,{type:'message',message:msg})}}if(m.type==='notification'){const n={id:String(m.id||Date.now()),text:String(m.text||'').slice(0,600),speak:Boolean(m.speak),from:name,at:Date.now()};if(n.text){room.notifications.push(n);room.notifications=room.notifications.slice(-20);broadcast(room,{type:'notification',notification:n},ws)}}if(m.type==='gps'&&Number.isFinite(m.lat)&&Number.isFinite(m.lon)){room.gps={lat:m.lat,lon:m.lon,accuracy:m.accuracy||null,speed:m.speed||null,heading:m.heading||null,at:Date.now(),name};broadcast(room,{type:'gps',gps:room.gps})}if(m.type==='state'&&m.state){room.state=m.state;broadcast(room,{type:'state',state:room.state},ws)}if(m.type==='status'){room.status=String(m.status||'planejando').slice(0,40);broadcast(room,{type:'status',status:room.status})}}catch{}});ws.on('close',()=>{room.clients.delete(ws);presence(room);if(room.clients.size===0)setTimeout(()=>{if(room.clients.size===0)rooms.delete(roomId)},1000*60*60*3)})});
const port=process.env.PORT||3000;server.listen(port,'0.0.0.0',()=>console.log(`Rota Daniel v4 online na porta ${port}`));
